from enum import Enum

EventOutcome = Enum('EventOutcome', ['BLOCK', 'TRAV','CHANCE'])
RobotType = Enum('RobotType', ['Ground', 'Drone'])
MAX_EDGE_LENGTH = 40.0
MIN_EDGE_LENGTH = 20.0
MAX_ISLAND_DISTANCE = 30.0
MIN_ISLAND_DISTANCE = 18.0
UAV_NUM = 1
MAX_UAV_ACTION = UAV_NUM
IV_SAMPLE_SIZE = 1000
BLOCK_COST = 0.0
STUCK_COST = 50.0
NOWAY_PEN = 300.0
VEL_RATIO = 3.0
APPROX_TIME = 1e-5
TRAV_LEVEL = 0.6
# REVISIT_PEN = 0.0
REVISIT_PEN = 20.0
ADD_IV = False
USE_HEURISTIC = False